```yaml
name: Báo cáo lỗi
description: Phát hiện lỗi? Hãy báo cáo tại đây!
title: "[LỖI] "
labels: ["bug"]
assignees: 
  - SwingTheVine
body:
  - type: markdown
    attributes:
      value: |
        Cảm ơn bạn đã dành thời gian điền vào mẫu này!
        **Bạn càng cung cấp nhiều thông tin, việc xác định và sửa lỗi sẽ càng dễ dàng hơn.**
        Nếu bạn muốn đọc hướng dẫn về cách báo cáo lỗi hiệu quả, bạn có thể [xem tại đây](https://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
  - type: checkboxes
    id: checked-bugs
    attributes:
      label: Bạn đã kiểm tra xem vấn đề này đã được báo cáo chưa?
      options:
        - label: Lỗi này chưa được báo cáo trước đây.
    validations:
      required: true
  - type: textarea
    id: describe-bug
    attributes:
      label: Mô tả lỗi
      description: "Mô tả những gì lỗi gây ra."
      placeholder: "Ví dụ: Khi tạo bản mẫu, ô trở thành màu đen."
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Hành vi mong đợi
      description: "Mô tả những gì bạn mong đợi sẽ xảy ra hoặc tại sao bạn nghĩ hành vi hiện tại là sai."
      placeholder: |
        Ví dụ: Khi tôi tạo bản mẫu, tôi mong đợi bản mẫu được lớp phủ lên trò chơi thay vì làm trò chơi bị đen.
        Ví dụ: Trò chơi không nên trở nên đen.
    validations:
      required: false
  - type: textarea
    id: things-tried
    attributes:
      label: Những điều bạn đã thử
      description: "Mô tả tất cả những điều bạn đã thử."
      placeholder: "Ví dụ: Tôi đã thử các bản mẫu có kích thước khác nhau. Tôi đã thử cập nhật Blue Marble."
    validations:
      required: false
  - type: textarea
    id: reproduce-bug
    attributes:
      label: Các bước tái hiện lỗi
      description: "Bạn thực hiện các bước nào để tái hiện lỗi?"
      placeholder: |
        Ví dụ:
        1. Tải trò chơi
        2. Lấy tọa độ (12, 194, 193, 3)
        3. Tạo bản mẫu tại tọa độ đó
        4. Trò chơi sẽ trở nên đen.
    validations:
      required: false
  - type: textarea
    id: error-message
    attributes:
      label: Thông báo lỗi
      description: "Nếu có, hãy thêm bất kỳ thông báo lỗi nào bạn nhận được."
      placeholder: "Ví dụ: Lỗi: Tọa độ bị sai định dạng! Bạn đã thử nhấp vào canvas trước chưa?"
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: Ảnh chụp màn hình
      description: "Nếu có, hãy thêm ảnh chụp màn hình để giúp giải thích vấn đề của bạn."
      placeholder: "Ví dụ: Một liên kết Imgur"
    validations:
      required: false
  - type: textarea
    id: system-information
    attributes:
      label: Thông tin hệ thống
      description: "Vui lòng điền các chi tiết về HĐH, phiên bản Blue Marble và trình duyệt web bạn sử dụng. Vui lòng điền đầy đủ!"
      placeholder: |
        HĐH: (Ví dụ: Windows)
        Phiên bản Blue Marble: 3.346.0
        Trình duyệt: Chrome
        Bạn đã tìm thấy một quả trứng Phục sinh :3
      value: |
        HĐH: 
        Phiên bản Blue Marble: 
        Trình duyệt: 
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Thông tin bổ sung
      description: "Thêm bất kỳ ngữ cảnh nào khác về vấn đề ở đây."
      placeholder: "Ví dụ: Lỗi này đã xảy ra từ phiên bản 3.245.0"
    validations:
      required: false
```
