name: Yêu cầu tính năng
description: Có ý tưởng bạn muốn thêm? Đề xuất tại đây!
title: "[TÍNH NĂNG] "
labels: ["enhancement"]
assignees: 
  - SwingTheVine
body:
  - type: markdown
    attributes:
      value: |
        ### Vui lòng không yêu cầu tính năng tự động đặt pixel mà không có tương tác của người dùng! 
        Cảm ơn bạn đã dành thời gian điền vào mẫu này!
  - type: textarea
    id: related-problem
    attributes:
      label: Yêu cầu tính năng của bạn có liên quan đến một vấn đề không? Vui lòng mô tả.
      description: "Mô tả vấn đề là gì."
      placeholder: |
        Ví dụ: Hầu hết các hình ảnh bản mẫu của tôi đều quá lớn.
        Ví dụ: Tôi muốn có cách để trò chuyện với mọi người.
    validations:
      required: false
  - type: textarea
    id: feature-solution
    attributes:
      label: Mô tả giải pháp bạn mong muốn
      description: "Mô tả những gì bạn muốn xảy ra."
      placeholder: |
        Ví dụ: Thêm tính năng thu phóng để tôi có thể làm nhỏ hình ảnh của mình.
        Ví dụ: Thêm cửa sổ trò chuyện để tôi có thể trò chuyện với người khác.
    validations:
      required: true
  - type: textarea
    id: feature-alternatives
    attributes:
      label: Mô tả các giải pháp thay thế bạn đã xem xét
      description: "Mô tả bất kỳ giải pháp hoặc tính năng thay thế nào bạn đã xem xét."
      placeholder: |
        Ví dụ: Thay vì tạo công cụ thay đổi kích thước hình ảnh, bạn có thể liên kết đến một công cụ khác.
        Ví dụ: Thay vì thêm cửa sổ trò chuyện, bạn có thể gắn tin nhắn vào pixel và xem chúng trên canvas!
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Ngữ cảnh bổ sung
      description: Thêm bất kỳ ngữ cảnh hoặc ảnh chụp màn hình nào khác về yêu cầu tính năng tại đây. Nếu tính năng của bạn dựa trên "một cái gì đó", vui lòng thêm bất kỳ liên kết nào liên quan đến "cái gì đó" đó tại đây.
      placeholder: |
        Ví dụ: Một hình ảnh (hoặc liên kết Imgur) về bản vẽ ý tưởng của bạn.
        Ví dụ: Một liên kết đến một thứ gì đó đã có tính năng của bạn. Đó có thể là một trò chơi điện tử, userscript, v.v.
    validations:
      required: false
